### ISSUE TITLE
unable to run request create

### ISSUE THREAD

**Issue by megawubs** [guyzmo/git-repo#147]
I just configured `git-repo`. My main goal is to use it to create merge requests from the command line. I have two different gitlab servers configured and both are giving this error when I run the `request create` sub command.

```
$ git vcs request create
Fatal error: request_create() takes from 6 to 8 positional arguments but 9 were given
```

**Comment by guyzmo** [comment]
hm… I thought I pushed a release with that being fixed. I'm about to make a new release this week end, and I believe that should already be fixed. You can try doing it with: `pip install https://github.com/guyzmo/git-repo`.

**Comment by megawubs** [comment]
that doesn't seem to fix it. I'm getting more errors now.

![image](https://cloud.githubusercontent.com/assets/2302867/25556988/3726adfe-2d08-11e7-824a-dbfc1eed6d4e.png)

**Comment by guyzmo** [comment]
I'm trying to solve this now, but it's quite a nightmare. Because of #27 I'm trying to loosen the dependencies, but for whatever reason, sometimes pip installs uritemplate 0.6 (which is API-incompatible with newer API >=2.0.0) for github3.py which git-repo relies on.. There's an issue [about that](https://github.com/sigmavirus24/uritemplate/issues/27).

And then I just found out there's another hicup: a dependency I'm relying on, pybitbucket depends on uritemplate 0.6. 😑

**Comment by guyzmo** [comment]
ok @megawubs, you can try again doing:

```
pip install git+https://github.com/guyzmo/git-repo@devel
```

I finally fixed the situation…

![](https://media.giphy.com/media/y9apAikClTPi/giphy.gif)

please, tell me if your original issue is actually fixed! 🙌

**Comment by megawubs** [comment]
I'm sorry, but i'm still getting the same error.  Made a asciinema recording of what I did. Check https://asciinema.org/a/9ux7qitn8rotu3ftz8072rn39

**Comment by guyzmo** [comment]
ok, try removing first the culprit dependencies

```bash
pip3 uninstall git-repo github3.py pybitbucket_fork uritemplate uritemplate.py
pip3 install git+https://github.com/guyzmo/git-repo@devel
```

**Comment by megawubs** [comment]
I did the uninstall and install as you said but it keeps failing out on me. It does give a different error this time.

<img width="1101" alt="schermafbeelding 2017-04-30 om 21 29 04" src="https://cloud.githubusercontent.com/assets/2302867/25567363/262d9370-2dec-11e7-955d-e8b46850e940.png">

**Comment by guyzmo** [comment]
ok, that's progress 😁

I'm integrating a branch that does a refactoring on requests, I'm triple checking that method manually as well as using the tests, for github, gitlab and bitbucket. I hope it's done by end of the week end (tomorrow is part of the week end 😉), so please, bear with me as I'm on it!

**Comment by megawubs** [comment]
Good luck! 👍

**Comment by guyzmo** [comment]
I just finished a full rewrite of the request create mechanism (which I was unhappy about, independantly of this regression you're hitting), and I *think* I got it right this time 😀 (it's only the third time I rewrote that one).

I still need to cook tests for it, merge them, and adapt that rewrite to the bitbucket branch. Thank you for the patience ☺

**Comment by megawubs** [comment]
I'll take a look at it! Just reinstall the develop branch and it should work?

**Comment by megawubs** [comment]
I'm still getting errors when making a merge request

![image](https://cloud.githubusercontent.com/assets/2302867/25605134/0ee172fe-2f09-11e7-88ae-ad0ff5484721.png)

**Comment by megawubs** [comment]
wait! It seems we were both doing something wrong. The help message gives the possible usage to run `git vcs request create` without any arguments but this does not work. It only works with both the `--title` and `--message`  arguments. Maybe update the usage list to reflect this change in api?

**Comment by guyzmo** [comment]
actually, I still haven't pushed the rewrite, but yes, `git vcs request create` is a rather new addition and that's what causing your error. My rewrite is improving on that and try to make the automagic more explicit and expectable.

**Comment by guyzmo** [comment]
(it was like 2am when I wrote my message earlier, and I was too tired to prepare the commits)

**Comment by megawubs** [comment]
Ok, I understand! Take your time. Let me know when I can test it out.

**Comment by guyzmo** [comment]
you can try again with devel:

```
pip3 install git+https://github.com/guyzmo/git-repo@devel
```

it's still warm out of the oven, so don't hesitate to report any issues you hit with it 😉

**Comment by megawubs** [comment]
I tested it today and I was able to create a merge request by just running `git vcs request create`. 🎉 

Just an idea: for the gitlab merge request you might add a check if to see if the branch starts with a number and by default add the text `closes #{number}` to the merge request description. I have a few other ideas as wel. Should I make an issue to describe them?

**Comment by guyzmo** [comment]
> if the branch starts with a number and by default add the text closes `#{number}` to the merge request description

I don't really think that's necessary, if you do a commit with `fixes #number` in a commit's body, it's already closing a ticket. When all the commits from a merge request is pushed the PR is closed.

> I have a few other ideas as well. Should I make an issue to describe them?

Sure don't hesitate! PRs are welcome too 😁 and don't hesitate to join the [git-repo channel on freenode](https://webchat.freenode.net/?channels=#git-repo) to discuss those ideas.
